apiVersion: v1
kind: Service
metadata:
  name: proj1
  namespace: proj1
  labels:
    app: proj1
spec:
  type: ClusterIP
  selector:
    app: proj1
  ports:
    - name: http
      port: 8051
      targetPort: 8501
      protocol: TCP
