apiVersion: apps/v1
kind: Deployment
metadata:
  name: proj1
  namespace: proj1
  labels:
    app: proj1
  annotations:
    argocd-image-updater.argoproj.io/image-list: proj1=harshitrai20/proj1-image
    argocd-image-updater.argoproj.io/proj1.update-strategy: latest
    argocd-image-updater.argoproj.io/proj1.allow-tags: regexp:^latest$
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proj1
  template:
    metadata:
      labels:
        app: proj1
    spec:
      containers:
        - name: proj1
          image: harshitrai20/laptop-price-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
